### ISSUE TITLE
zipinfo differences

### ISSUE THREAD

**Issue by obfusk** [obfusk/reproducible-apk-tools#10]
## TODO

- [ ] `T`/`B` for encrypted files
- [ ] `NN.N%` rounding differences

## good

- [x] `defS`, `defF`, `defX`
- [x] extended fat file permissions (e.g. `-r--a--`, `-rw-a--`, `-rwxa--`)
- [x] executable permission for `.com`/`.exe`/`.btm`/`.cmd`/`.bat` (fat)
- [x] `ntf`
- [x] `d` for directories (fat) [NB: `--extended` treats filenames ending w/ `/` as dirs]
- [x] `atime`, `ctime`

## wontfix

- [ ] #9
